const types = {
    FETCH_APPEALS: "FETCH_APPEALS",
    CHANGE_SEARCH_INPUT: "CHANGE_SEARCH_INPUT",
    ADD_NEW_CREATED: "ADD_NEW_CREATED",
    DELETE_APPEAL: "DELETE_APPEAL",
    SHOW_MODAL: "SHOW_MODAL",
    UPDATE_APPEAL: "UPDATE_APPEAL"
}

export default types;
